### ISSUE TITLE
Segfault with starting values

### ISSUE THREAD

**Issue by blegat** [MOSEK/Mosek.jl#222] opened 2022-10-20 09:06 UTC
Mosek gives a segmentation fault with the test `test_constraint_PrimalStart_DualStart_SecondOrderCone` of MOI. See the segfault here:
https://github.com/jump-dev/MosekTools.jl/actions/runs/3243196430/jobs/5317555832#step:7:132
and the excluded test here:
https://github.com/jump-dev/MosekTools.jl/blob/53ede41977b8ef5d604b03643875329acc601b86/test/runtests.jl#L103-L104
Since MosekTools.jl does not call C directly, this is either a bug in Mosek.jl or the MOSEK library itself.

To reproduce, do
```julia
import MathOptInterface
const MOI = MathOptInterface
using MosekTools
optimizer = Mosek.Optimizer()
MOI.set(optimizer, MOI.RawOptimizerAttribute("fallback"), "mosek://solve.mosek.com:30080")
MOI.Test.test_constraint_PrimalStart_DualStart_SecondOrderCone(optimizer, MOI.Test.Config())
```
without setting the fallback url, there does not seem to be any segfault.

**Comment by ulfworsoe** [comment] 2022-10-20 11:51
Confirmed.

**Comment by ulfworsoe** [comment] 2022-10-21 12:33
This turned out to be an internal issue in MOSEK. It is a combination of a reader and a writer bug, so it will work when a new distro is out AND the backend solver has been updated on `solve.mosek.com`. I'll close the issue when everything is updated.

**Comment by blegat** [comment] 2022-10-24 11:30
Thanks, I'll try to reenable the tests on MosekTools.jl once this issue is closed.

**Comment by ulfworsoe** [comment] 2022-10-24 18:31
There is a new MOSEK build and the solve.mosek.com has been opdated. There is no new Mosek.jl release since it was purely an internal MOSEK issue, so to test it is necessary rebuild the Mosek.jl package so the new distro is downloaded. Tests starting with a clean slate should work now.
I'll close the issue. If the problem remains, please reopen.

**Closed by ulfworsoe** 2022-10-24 18:31 UTC
